remote_theme: fluffyemily/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//gcanti.github.io/fp-ts/"
  "API Reference":
    - "//gcanti.github.io/fp-ts/modules/"
  "GitHub":
    - "//github.com/gcanti/fp-ts"
